language: android
android:
  components:
     - tools
     - platform-tools
     - android-29
     - build-tools-29.0.2

branches:
  only:
    - master

after_success:
- ./gradlew test

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "platforms;android-28"